export const modernStyle = {
  input: {
    padding: "10px 12px",
    fontSize: 15,
    border: "1px solid #ccc",
    borderRadius: 4,
    fontFamily: "inherit",
  },
  button: {
    padding: "10px",
    fontSize: 16,
    backgroundColor: "#4CAF50",
    color: "white",
    border: "none",
    borderRadius: 4,
    cursor: "pointer",
  },
  sectionTitle: {
    fontSize: 18,
    marginBottom: 10,
    borderBottom: "1px solid #ddd",
    paddingBottom: 4,
  },
  sectionContent: {
    fontSize: 15,
    whiteSpace: "pre-wrap",
    lineHeight: 1.6,
  },
  previewContainer: {
    minHeight: 600,
    backgroundColor: "#fdfdfd",
    boxShadow: "0 0 10px rgba(0,0,0,0.1)",
    padding: "40px 50px",
    margin :'',
    fontFamily: "Arial, sans-serif",
    color: "#333",
  },
    chipList: {
  display: 'flex',
  flexWrap: 'wrap',
  gap: '8px',
  marginTop: '8px',
}as React.CSSProperties,
chip: {
  padding: '4px 12px',
  backgroundColor: '#e1e8f0',
  color: '#334e68',
  borderRadius: '16px',
  fontSize: '13px',
  lineHeight: '1.5',
},
};
